pref("extensions.zoteroAnnotAI.enabled", true);
pref("extensions.zoteroAnnotAI.lastLifecycleEvent", "");
pref("extensions.zoteroAnnotAI.provider.type", "openai-compatible");
pref("extensions.zoteroAnnotAI.provider.name", "Default OpenAI-compatible");
pref("extensions.zoteroAnnotAI.provider.baseURL", "");
pref("extensions.zoteroAnnotAI.provider.model", "");
pref("extensions.zoteroAnnotAI.provider.apiKey", "");
pref("extensions.zoteroAnnotAI.provider.timeoutMs", 30000);
pref("extensions.zoteroAnnotAI.provider.enableStreaming", false);
pref("extensions.zoteroAnnotAI.provider.lastTestStatus", "");
pref("extensions.zoteroAnnotAI.annotation.translate.type", "highlight");
pref("extensions.zoteroAnnotAI.annotation.translate.color", "#e56eee");
pref("extensions.zoteroAnnotAI.annotation.explain.type", "highlight");
pref("extensions.zoteroAnnotAI.annotation.explain.color", "#5fb236");
pref("extensions.zoteroAnnotAI.annotation.qa.type", "highlight");
pref("extensions.zoteroAnnotAI.annotation.qa.color", "#f19837");
